### ISSUE TITLE
Dynamic width or text size

### ISSUE THREAD

**Issue by lifeparticle** [lifeparticle/Gist-Count#3]

**Comment by MichaelDimmitt** [comment]
Pr incoming to change svg width based on username length with an upper limit of 39 characters 
which is the github maximum

<img width="336" alt="Screen Shot 2022-08-29 at 9 47 07 AM" src="https://user-images.githubusercontent.com/11463275/187216173-e0dc1f6e-eb0a-4690-84b1-2d4ea60268f4.png">

**Comment by lifeparticle** [comment]
That would be great, thank you @MichaelDimmitt
